name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Ganti 'main' ke 'master' jika branch utamamu 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN" --project smartmindjaya
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
